pipeline {
    agent any
    stages {
        stage('Add rules') {
          steps {
            sh "chmod +x -R ${env.WORKSPACE}"
          }
        }
        stage('Info') {
            steps {
                sh './jenkins/scripts/info.sh'
            }
        }
        stage('Installation') {
            steps {
                sh './jenkins/scripts/installation.sh'
            }
        }
        stage('Build') {
            steps {
                sh './jenkins/scripts/build.sh'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
    }
}